<?php
/*
 本代码由 旗舰猫www.7jcat.com 创建
 创建时间 2020-06-12 10:13:56
 技术支持 QQ:2029336034 Mail:cold-cat-studio@foxmail.com
 严禁反编译、逆向等任何形式的侵权行为，违者将追究法律责任
*/

namespace App\Http\Controllers\Api;if(!defined("A_A_AA_A_AA"))define("A_A_AA_A_AA","A_A_AA_AA__");$GLOBALS[A_A_AA_A_AA]=explode("|A|h|5", "A_A_A_A_A_A");if(!defined("A_A_AA__AAA"))define("A_A_AA__AAA","A_A_AA_A___");$GLOBALS[A_A_AA__AAA]=explode("|e|0|f", "limit|e|0|f10|e|0|fpage|e|0|f1|e|0|fuser_id|e|0|f=|e|0|ftype|e|0|fcreated_time|e|0|fdesc|e|0|fdata|e|0|flimit|e|0|fpage");if(!defined("A_A_AA_____"))define("A_A_AA_____","A_A_AA____A");$GLOBALS[A_A_AA_____]=explode("|j|W|X", "A_A_A_AAAAA|j|W|Xdate|j|W|Xto_user_id|j|W|X=|j|W|Xcreate_time|j|W|Xdesc|j|W|XY-m-d H:i:s");if(!defined($GLOBALS[A_A_AA_A_AA][00]))define($GLOBALS[A_A_AA_A_AA][00], ord(4));use Illuminate\Http\Request;use App\PrizePoolcopy;use App\Users;use App\AccountLog;use Illuminate\Support\Facades\Input;use App\DAO\FactprofitsDAO;class PrizePoolController extends Controller{public function test555(){$L358M=new FactprofitsDAO();unset($L35tI8N);$A_A_A_AA___=$L358M;$L35vP8M=67*A_A_A_A_A_A;$L35vP8N=$L35vP8M-3483;$L35hC0=call_user_func_array(array($A_A_A_AA___,"Profit_loss_release"),array(&$L35vP8N));}public function candyhistory(){unset($L35tI8M);$L35tI8M=$GLOBALS[A_A_AA_____][01];$GLOBALS[$GLOBALS[A_A_AA_____][0x0]]=$L35tI8M;unset($L35tI8M);$A_A_A_AA_AA=Users::getUserId();unset($L35tI8M);$A_A_A_AAA__=PrizePoolcopy::where($GLOBALS[A_A_AA_____][0x2],$GLOBALS[A_A_AA_____][3],$A_A_A_AA_AA)->orderBy($GLOBALS[A_A_AA_____][0x4],$GLOBALS[A_A_AA_____]{05})->get()->toArray();foreach($A_A_A_AAA__ as $A_A_A_AAA_A=>$A_A_A_AAAA_){unset($L35tI8M);$L35tI8M=$GLOBALS[$GLOBALS[A_A_AA_____][0x0]]($GLOBALS[A_A_AA_____][06],$A_A_A_AAAA_[$GLOBALS[A_A_AA_____][0x4]]);$A_A_A_AAA__[$A_A_A_AAA_A][$GLOBALS[A_A_AA_____][0x4]]=$L35tI8M;}$L35hC0=call_user_func_array(array($this,"success"),array(&$A_A_A_AAA__));return $L35hC0;}public function candy_tousdthistory(){unset($L35tI8M);$A_A_AA___A_=Input::get($GLOBALS[A_A_AA__AAA]{00},$GLOBALS[A_A_AA__AAA][0x1]);unset($L35tI8M);$A_A_AA___AA=Input::get($GLOBALS[A_A_AA__AAA][2],$GLOBALS[A_A_AA__AAA][03]);unset($L35tI8M);$A_A_AA__A__=Users::getUserId();unset($L35tI8M);$A_A_AA__A_A=AccountLog::CANDY_TOUSDT_CANDY;unset($L35tI8M);$A_A_AA__AA_=AccountLog::where($GLOBALS[A_A_AA__AAA]{4},$GLOBALS[A_A_AA__AAA][05],$A_A_AA__A__)->where($GLOBALS[A_A_AA__AAA]{0x6},$GLOBALS[A_A_AA__AAA][05],$A_A_AA__A_A)->orderBy($GLOBALS[A_A_AA__AAA][0x7],$GLOBALS[A_A_AA__AAA][0x8])->paginate($A_A_AA___A_);$L35hCvPvP0=call_user_func_array(array($A_A_AA__AA_,"items"),array());$L35zAvP1=array();$L35zAvP1[$GLOBALS[A_A_AA__AAA][0x9]]=$L35hCvPvP0;$L35zAvP1[$GLOBALS[A_A_AA__AAA][10]]=$A_A_AA___A_;$L35zAvP1[$GLOBALS[A_A_AA__AAA][0xB]]=$A_A_AA___AA;return $this->success($L35zAvP1);}}
?>